import type { Metadata } from "next";
import { Alexandria, Inter, Montserrat, Nunito_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import React from "react";
import ChatBot from "@/app/ChatBot";
import { SpeedInsights } from "@vercel/speed-insights/next"

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "700", "600"]
});

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "700", "600"]
});

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "700", "600"]
});


const nunito = Nunito_Sans({
    variable: "--font-nunito",
    subsets: ["latin"],
    weight: ["300", "400", "500", "700", "600"]
});

const alexandria = Alexandria({
    variable: "--font-alex",
    subsets: ["latin"],
    weight: ["100", "200", "400", "500", "600", "700", "800"]
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body

                className={`antialiased ${alexandria.variable} overflow-x-hidden overflow-y-scroll w-full ${poppins.variable} ${nunito.variable} ${montserrat.variable} ${inter.variable}`}>
            <main className={"z-[9999999999999] relative"}>
                    <ToastContainer />
                </main>
                <main className={""}>
                    <ChatBot>
                        {children}
                    </ChatBot>
                </main>
            <SpeedInsights/>
            </body>
        </html>
    );
}
